---
- name: Win-deploy
  hosts: all
  tasks:
          - name: Install IIS (Web-Server only)
            win_feature:
              name: Web-Server
              state: present
            when: ACTION == "iis"     
            
          - name: Ping Server
            win_ping:
            when: ACTION == "ping"
