---
- name: Win-deploy
  hosts: all
  tasks:
          - name: Install IIS (Web-Server only)
            win_feature:
              name: Web-Server
              state: present
            tags:
            - iis
            
          - name: Ping Server
            win_ping:
            tags: 
            - ping
