---
- name: win_reboot 
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: reboot host(s)
      win_reboot:
        msg: "reboot by Ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 10
