---
- hosts: all
  become: false
  gather_facts: false
  tasks: 
  - name: Remove registry path MyCompany (including all entries it contains)
    win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\test
    state: absent
    delete_key: yes
